### PR TITLE
Persistent requests support

### LINKED ISSUE #10: Connection to peer(s) drop unexpectedly sometimes
I noticed that sometimes the node closes the connection to the peer(s) unexpectedly. For regtest this causes the node to basically being isolated from the network, and, in fact, it does not notify about new txs of interest in such cases.

Screenshot 2022-03-16 at 18 11 16

### LINKED ISSUE #11: ScanRequest persistent watch
At the moment, when a request related to a watched item is solved, it's removed from the queue of requests, meaning that the item is basically watched only once. This requires the client making use of this service to add logic to eventually re-watch an item for a "persistent watch". Check [here](https://github.com/vulpemventures/ocean/pull/11#discussion_r832054882) for more info.

The proposal is to add a new field in `ScanRequest`:
```
type ScanRequest struct {
	StartHeight uint32    // nil means scan from genesis block
	Item        WatchItem // item to watch
        PersistentWatch bool // whether keep watching the item 
}

```
and related option `WithPersistentWatch()` in order to have a single place for this re-watching logic. Clients would just use this new option instead of being forced to implement it.

### PR DESCRIPTION
**Pull request by louisinger**
Persistent request behavior:
* the scanner resolves a request at block height H (`report.BlockHeight = H`)
* after sending the report, the scanner checks `IsPersistent` request's member
* if `IsPersistent = true` the scanner watch again the resolved WatchItem but with `StartHeight = H+1`.

--

* new RequestOption lets to create persistent request : `WithPersistent()`
* add `scanner_test.go` (integration testing for Watch on nigiri regtest).
* BONUS: increase the pong timeout (30sec -> 60sec) related to #10 

Closes #10 
Closes #11 

@altafan please review

### CODE REVIEW

File: pkg/scanner/request.go [hunk 1]
```diff
@@ -19,10 +20,17 @@ func WithStartBlock(blockHeight uint32) ScanRequestOption {
 	}
 }
 
+func WithPersistent() ScanRequestOption {
```
Comment (altafan) [inline pkg/scanner/request.go]:
```suggestion
func WithPersistentWatch() ScanRequestOption {
```

File: pkg/scanner/request.go [hunk 2]
```diff
@@ -19,10 +20,17 @@ func WithStartBlock(blockHeight uint32) ScanRequestOption {
...
+}
+
 func newScanRequest(options ...ScanRequestOption) *ScanRequest {
 	req := &ScanRequest{
-		Item:        nil,
-		StartHeight: 0,
+		Item:         nil,
+		StartHeight:  0,
+		IsPersistent: false,
 	}
```
Comment (altafan) [inline pkg/scanner/request.go]: No need to specify the "zero" for every field, this can just be:

```suggestion
        req := &ScanRequest{}
```

**Review by altafan — APPROVED** [review]
